version: "3.2"

services:
  postgres:
    image: postgres:11
    restart: unless-stopped
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DEBUG=1
    ports:
      - 8000:8000
    volumes:
      - ./src:/code
    depends_on:
      - postgres
